get_filename_component(directory "${EXE}" DIRECTORY)
if(FAIL_INITIALIZE)
    set(marker "${directory}/shutdown-failure.txt")
    set(args --config "${CONFIG_FILE}" --smoke-test=2 --no-vsync)
else()
    set(marker "${directory}/shutdown-normal.txt")
    set(args --smoke-test=10000 --no-vsync)
endif()
file(REMOVE "${marker}")
execute_process(COMMAND "${EXE}" ${args} WORKING_DIRECTORY "${directory}" RESULT_VARIABLE result TIMEOUT 50)
if(FAIL_INITIALIZE)
    if(NOT result EQUAL 1)
        message(FATAL_ERROR "Expected initialization failure, got ${result}")
    endif()
elseif(NOT result EQUAL 0)
    message(FATAL_ERROR "Infrastructure failed: ${result}")
endif()
if(NOT EXISTS "${marker}")
    message(FATAL_ERROR "Shutdown was not invoked")
endif()
file(READ "${marker}" contents)
if(NOT contents STREQUAL "device-alive")
    message(FATAL_ERROR "Device was not available during Shutdown")
endif()
