function(prism_target_defaults target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /utf-8 /external:anglebrackets /external:W0)
    endif()
endfunction()

function(prism_add_target name)
    cmake_parse_arguments(P "" "KIND;CONFIG;SHADER_MODEL" "SOURCES;SHADERS;INCLUDES;LINK;SHADER_OPTIONS" ${ARGN})
    # Fail loudly: a silently ignored argument looks like a configured option that never took effect.
    if(P_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "prism_add_target(${name}): unknown arguments: ${P_UNPARSED_ARGUMENTS}")
    endif()
    if(P_KIND STREQUAL "EXECUTABLE")
        add_executable(${name} WIN32 ${P_SOURCES})
        target_link_libraries(${name} PRIVATE prism_app ${P_LINK})
        set_property(TARGET ${name} PROPERTY PRISM_DEPENDENCIES prism_app ${P_LINK})
    else()
        add_library(${name} STATIC ${P_SOURCES})
        target_link_libraries(${name} PUBLIC prism_render ${P_LINK})
        set_property(TARGET ${name} PROPERTY PRISM_DEPENDENCIES prism_render ${P_LINK})
    endif()
    prism_target_defaults(${name})
    if(P_INCLUDES)
        target_include_directories(${name} PUBLIC ${P_INCLUDES})
    endif()
    if(P_SHADERS)
        prism_add_shader_package(${name} SHADERS ${P_SHADERS} INCLUDES ${P_INCLUDES}
            SHADER_MODEL "${P_SHADER_MODEL}" SHADER_OPTIONS ${P_SHADER_OPTIONS})
        set_property(TARGET ${name} PROPERTY PRISM_SHADER_PACKAGES ${name})
        add_dependencies(${name} ${name}Shaders)
    endif()
    if(P_KIND STREQUAL "EXECUTABLE")
        prism_write_shader_manifest(${name})
    endif()
    if(P_CONFIG)
        get_filename_component(config "${P_CONFIG}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        add_custom_command(TARGET ${name} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
            "${config}" "$<TARGET_FILE_DIR:${name}>/${name}.json")
    endif()
endfunction()
