# A package owns entry points, compilation settings and one virtual shader root.
function(prism_add_shader_package name)
    cmake_parse_arguments(P "" "SHADER_MODEL" "SHADERS;INCLUDES;SHADER_OPTIONS" ${ARGN})
    if(NOT P_SHADER_MODEL)
        set(P_SHADER_MODEL 6_5)
    endif()
    set(cfg "${CMAKE_CURRENT_BINARY_DIR}/${name}.shaders.cfg")
    set(lines "")
    set(sources "")
    set(basenames "")
    foreach(entry IN LISTS P_SHADERS)
        string(REPLACE ":" ";" parts "${entry}")
        list(GET parts 0 source)
        list(GET parts 1 stage)
        list(LENGTH parts count)
        set(point "main_${stage}")
        if(count EQUAL 3)
            list(GET parts 2 point)
        elseif(NOT count EQUAL 2)
            message(FATAL_ERROR "Shader entry must be file:stage[:entry]: ${entry}")
        endif()
        get_filename_component(source "${source}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        get_filename_component(base "${source}" NAME)
        if(base IN_LIST basenames AND NOT source IN_LIST sources)
            message(FATAL_ERROR "Duplicate shader filename in ${name}: ${base}")
        endif()
        list(APPEND basenames "${base}")
        list(APPEND sources "${source}")
        string(APPEND lines "${source} -T ${stage}")
        if(NOT stage STREQUAL "lib")
            string(APPEND lines " -E ${point}")
        endif()
        string(APPEND lines "\n")
    endforeach()
    file(WRITE "${cfg}" "${lines}")
    set(includes "${PRISM_SHADER_INCLUDE}" ${P_INCLUDES})
    list(JOIN P_SHADER_OPTIONS " " options)
    donut_compile_shaders(TARGET ${name}Shaders PROJECT_NAME "${name}" CONFIG "${cfg}"
        SOURCES ${sources} DXIL "${PRISM_RUNTIME_DIR}/shaders/prism/dxil/${name}"
        INCLUDES ${includes} SHADER_MODEL ${P_SHADER_MODEL}
        SHADERMAKE_OPTIONS "${options}" SHADERMAKE_OPTIONS_DXIL "--flatten" FOLDER "Prism/Shaders")
    set(include_args "")
    foreach(dir IN LISTS includes DONUT_SHADER_INCLUDE_DIR)
        string(APPEND include_args " -I \"${dir}\"")
    endforeach()
    file(GENERATE OUTPUT "${PRISM_RUNTIME_DIR}/.shader-packages/${name}.cmake" CONTENT
"execute_process(COMMAND \"$<TARGET_FILE:ShaderMake>\" --config \"${cfg}\" --out \"\${PRISM_RELOAD_OUTPUT}\" --platform DXIL --binaryBlob --outputExt .bin --flatten -D TARGET_D3D12 --compiler \"${SHADERMAKE_DXC_PATH}\" --shaderModel ${P_SHADER_MODEL}${include_args} ${options}
    RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR \"Shader package ${name} failed\")
endif()
")
endfunction()

function(prism_collect_shader_packages target output)
    set(result "")
    if(TARGET ${target})
        get_target_property(own ${target} PRISM_SHADER_PACKAGES)
        if(own)
            list(APPEND result ${own})
        endif()
        get_target_property(dependencies ${target} PRISM_DEPENDENCIES)
        foreach(dependency IN LISTS dependencies)
            if(TARGET ${dependency})
                prism_collect_shader_packages(${dependency} nested)
                list(APPEND result ${nested})
            endif()
        endforeach()
    endif()
    list(REMOVE_DUPLICATES result)
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

function(prism_write_shader_manifest target)
    prism_collect_shader_packages(${target} packages)
    set(manifest "{\"version\":1,\"packages\":[")
    set(script "if(NOT DEFINED PRISM_RELOAD_OUTPUT)\n message(FATAL_ERROR \"PRISM_RELOAD_OUTPUT is required\")\nendif()\nset(stage_root \"\${PRISM_RELOAD_OUTPUT}\")\n")
    set(comma "")
    foreach(package IN LISTS packages)
        add_dependencies(${target} ${package}Shaders)
        string(APPEND manifest "${comma}{\"name\":\"${package}\",\"virtualRoot\":\"/shaders/prism/${package}\",\"buildScript\":\".shader-packages/${package}.cmake\"}")
        set(comma ",")
        string(APPEND script "set(PRISM_RELOAD_OUTPUT \"\${stage_root}/${package}\")\ninclude(\"\${CMAKE_CURRENT_LIST_DIR}/.shader-packages/${package}.cmake\")\n")
    endforeach()
    string(APPEND manifest "]}\n")
    file(GENERATE OUTPUT "${PRISM_RUNTIME_DIR}/${target}.shaders.json" CONTENT "${manifest}")
    file(GENERATE OUTPUT "${PRISM_RUNTIME_DIR}/${target}.reload.cmake" CONTENT "${script}")
endfunction()
